# Generated by Django 5.1.1 on 2024-09-09 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal", models.CharField(max_length=200, unique=True)),
                ("desc", models.CharField(max_length=2000)),
                ("price", models.DecimalField(decimal_places=2, max_digits=2)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("starters", "Starters"),
                            ("salades", "Salades"),
                            ("mean_dishes", "Mean Dishes"),
                            ("desserts", "Desserts"),
                        ],
                        max_length=500,
                    ),
                ),
                (
                    "available",
                    models.IntegerField(
                        choices=[(0, "Unavailable"), (1, "Available")], default=0
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
