# Generated by Django 5.1.1 on 2024-09-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_menu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="available",
        ),
        migrations.AddField(
            model_name="item",
            name="is_available",
            field=models.IntegerField(choices=[(0, "no"), (1, "yes")], default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
